<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_make_appointment_btn</name>
   <tag></tag>
   <elementGuidId>6f60643e-5e74-4b17-8e48-40c50e42cde1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a#btn-make-appointment</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
