<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_book_appointment</name>
   <tag></tag>
   <elementGuidId>7ffcff88-fa42-4e6f-b4f9-2703df957bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button#btn-book-appointment</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
